//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Breas.Device.Vivo {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VivoDeviceKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VivoDeviceKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Breas.Device.Vivo.VivoDeviceKeys", typeof(VivoDeviceKeys).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Adjustment in Home.
        /// </summary>
        public static string AdjustmentInHome {
            get {
                return ResourceManager.GetString("AdjustmentInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 0-31.
        /// </summary>
        public static string AlarmMask0_31 {
            get {
                return ResourceManager.GetString("AlarmMask0_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info 128-159.
        /// </summary>
        public static string AlarmMask128_159 {
            get {
                return ResourceManager.GetString("AlarmMask128_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 32-63.
        /// </summary>
        public static string AlarmMask32_63 {
            get {
                return ResourceManager.GetString("AlarmMask32_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 64-95.
        /// </summary>
        public static string AlarmMask64_95 {
            get {
                return ResourceManager.GetString("AlarmMask64_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 96-127.
        /// </summary>
        public static string AlarmMask96_127 {
            get {
                return ResourceManager.GetString("AlarmMask96_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Alarm Sound Level.
        /// </summary>
        public static string AlarmSoundLevel {
            get {
                return ResourceManager.GetString("AlarmSoundLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string AudioMute {
            get {
                return ResourceManager.GetString("AudioMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P Breath Mode.
        /// </summary>
        public static string BreathMode {
            get {
                return ResourceManager.GetString("BreathMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Circuit Recognition.
        /// </summary>
        public static string CircuitRecognition {
            get {
                return ResourceManager.GetString("CircuitRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clickon Bat Capacity.
        /// </summary>
        public static string ClickonBatCapacity {
            get {
                return ResourceManager.GetString("ClickonBatCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clickon Bat Status.
        /// </summary>
        public static string ClickonBatStatus {
            get {
                return ResourceManager.GetString("ClickonBatStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Current Circuit.
        /// </summary>
        public static string CurrentCircuit {
            get {
                return ResourceManager.GetString("CurrentCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Device Mode.
        /// </summary>
        public static string DeviceMode {
            get {
                return ResourceManager.GetString("DeviceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Log.
        /// </summary>
        public static string EraseLogs {
            get {
                return ResourceManager.GetString("EraseLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O EtCO2 Unit.
        /// </summary>
        public static string EtCO2Unit {
            get {
                return ResourceManager.GetString("EtCO2Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int Bat Capacity.
        /// </summary>
        public static string IntBatCapacity {
            get {
                return ResourceManager.GetString("IntBatCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int Bat Status.
        /// </summary>
        public static string IntBatStatus {
            get {
                return ResourceManager.GetString("IntBatStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M CO2 sensor atm. pres..
        /// </summary>
        public static string MeasurementCO2AtmPress {
            get {
                return ResourceManager.GetString("MeasurementCO2AtmPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Delta Vol.
        /// </summary>
        public static string MeasurementDV {
            get {
                return ResourceManager.GetString("MeasurementDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M EtCO2.
        /// </summary>
        public static string MeasurementEtCO2 {
            get {
                return ResourceManager.GetString("MeasurementEtCO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M EtCO2 On / Off.
        /// </summary>
        public static string MeasurementEtCO2OnOff {
            get {
                return ResourceManager.GetString("MeasurementEtCO2OnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M FiO2.
        /// </summary>
        public static string MeasurementFiO2 {
            get {
                return ResourceManager.GetString("MeasurementFiO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M FiO2 On / Off.
        /// </summary>
        public static string MeasurementFiO2OnOff {
            get {
                return ResourceManager.GetString("MeasurementFiO2OnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M I:E.
        /// </summary>
        public static string MeasurementIE {
            get {
                return ResourceManager.GetString("MeasurementIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M InspCO2.
        /// </summary>
        public static string MeasurementInspCO2 {
            get {
                return ResourceManager.GetString("MeasurementInspCO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Insp Time.
        /// </summary>
        public static string MeasurementInspTime {
            get {
                return ResourceManager.GetString("MeasurementInspTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Leakage.
        /// </summary>
        public static string MeasurementLeakage {
            get {
                return ResourceManager.GetString("MeasurementLeakage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string MeasurementMute {
            get {
                return ResourceManager.GetString("MeasurementMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M MV.
        /// </summary>
        public static string MeasurementMV {
            get {
                return ResourceManager.GetString("MeasurementMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M MVe.
        /// </summary>
        public static string MeasurementMvE {
            get {
                return ResourceManager.GetString("MeasurementMvE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M MVi.
        /// </summary>
        public static string MeasurementMvI {
            get {
                return ResourceManager.GetString("MeasurementMvI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M PEEP.
        /// </summary>
        public static string MeasurementPeep {
            get {
                return ResourceManager.GetString("MeasurementPeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M % Spont.
        /// </summary>
        public static string MeasurementPercentSpont {
            get {
                return ResourceManager.GetString("MeasurementPercentSpont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M % in TV.
        /// </summary>
        public static string MeasurementPercentTV {
            get {
                return ResourceManager.GetString("MeasurementPercentTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M PMean.
        /// </summary>
        public static string MeasurementPMean {
            get {
                return ResourceManager.GetString("MeasurementPMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Source.
        /// </summary>
        public static string MeasurementPowerSource {
            get {
                return ResourceManager.GetString("MeasurementPowerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M PPeak.
        /// </summary>
        public static string MeasurementPPeak {
            get {
                return ResourceManager.GetString("MeasurementPPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Pulse.
        /// </summary>
        public static string MeasurementPulse {
            get {
                return ResourceManager.GetString("MeasurementPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Rise Time.
        /// </summary>
        public static string MeasurementRiseTime {
            get {
                return ResourceManager.GetString("MeasurementRiseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M SpO2.
        /// </summary>
        public static string MeasurementSpO2 {
            get {
                return ResourceManager.GetString("MeasurementSpO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M SpO2 On / Off.
        /// </summary>
        public static string MeasurementSpO2OnOff {
            get {
                return ResourceManager.GetString("MeasurementSpO2OnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Spont Rate.
        /// </summary>
        public static string MeasurementSpontRate {
            get {
                return ResourceManager.GetString("MeasurementSpontRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Total Rate.
        /// </summary>
        public static string MeasurementTotalRate {
            get {
                return ResourceManager.GetString("MeasurementTotalRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Type.
        /// </summary>
        public static string MeasurementTriggerType {
            get {
                return ResourceManager.GetString("MeasurementTriggerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Vt.
        /// </summary>
        public static string MeasurementVt {
            get {
                return ResourceManager.GetString("MeasurementVt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Vte.
        /// </summary>
        public static string MeasurementVtE {
            get {
                return ResourceManager.GetString("MeasurementVtE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Vti.
        /// </summary>
        public static string MeasurementVtI {
            get {
                return ResourceManager.GetString("MeasurementVtI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Patient Mode.
        /// </summary>
        public static string PatientMode {
            get {
                return ResourceManager.GetString("PatientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot Treatment Hours.
        /// </summary>
        public static string PatientOperatingTime {
            get {
                return ResourceManager.GetString("PatientOperatingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Pressure Unit.
        /// </summary>
        public static string PressureUnit {
            get {
                return ResourceManager.GetString("PressureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Profile 1 Activated.
        /// </summary>
        public static string Profile1Activated {
            get {
                return ResourceManager.GetString("Profile1Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Profile 2 Activated.
        /// </summary>
        public static string Profile2Activated {
            get {
                return ResourceManager.GetString("Profile2Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Profile 3 Activated.
        /// </summary>
        public static string Profile3Activated {
            get {
                return ResourceManager.GetString("Profile3Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileName.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Selected Profile.
        /// </summary>
        public static string SelectedProfile {
            get {
                return ResourceManager.GetString("SelectedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Apnea Alarm.
        /// </summary>
        public static string SettingApneaAlarm {
            get {
                return ResourceManager.GetString("SettingApneaAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Backup Rate.
        /// </summary>
        public static string SettingBackupRate {
            get {
                return ResourceManager.GetString("SettingBackupRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Breath Rate High Alarm.
        /// </summary>
        public static string SettingBreathRateHighAlarm {
            get {
                return ResourceManager.GetString("SettingBreathRateHighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Breath Rate Low Alarm.
        /// </summary>
        public static string SettingBreathRateLowAlarm {
            get {
                return ResourceManager.GetString("SettingBreathRateLowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T CPAP.
        /// </summary>
        public static string SettingCpap {
            get {
                return ResourceManager.GetString("SettingCpap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A EtCO2 High Alarm.
        /// </summary>
        public static string SettingEtCO2HighAlarm {
            get {
                return ResourceManager.GetString("SettingEtCO2HighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A EtCO2 High Alarm(kPa).
        /// </summary>
        public static string SettingEtCO2HighAlarmKpa {
            get {
                return ResourceManager.GetString("SettingEtCO2HighAlarmKpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A EtCO2 High Alarm(mmHg).
        /// </summary>
        public static string SettingEtCO2HighAlarmMmhg {
            get {
                return ResourceManager.GetString("SettingEtCO2HighAlarmMmhg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A EtCO2 High Alarm(%).
        /// </summary>
        public static string SettingEtCO2HighAlarmPerc {
            get {
                return ResourceManager.GetString("SettingEtCO2HighAlarmPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A EtCO2 Low Alarm.
        /// </summary>
        public static string SettingEtCO2LowAlarm {
            get {
                return ResourceManager.GetString("SettingEtCO2LowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A EtCO2 Low Alarm(kPa).
        /// </summary>
        public static string SettingEtCO2LowAlarmKpa {
            get {
                return ResourceManager.GetString("SettingEtCO2LowAlarmKpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A EtCO2 Low Alarm(mmHg).
        /// </summary>
        public static string SettingEtCO2LowAlarmMmhg {
            get {
                return ResourceManager.GetString("SettingEtCO2LowAlarmMmhg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A EtCO2 Low Alarm(%).
        /// </summary>
        public static string SettingEtCO2LowAlarmPerc {
            get {
                return ResourceManager.GetString("SettingEtCO2LowAlarmPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O EtCO2 Unit.
        /// </summary>
        public static string SettingEtCO2Unit {
            get {
                return ResourceManager.GetString("SettingEtCO2Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Exp Trig.
        /// </summary>
        public static string SettingExpTrigger {
            get {
                return ResourceManager.GetString("SettingExpTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Flow High Alarm.
        /// </summary>
        public static string SettingFiO2HighAlarm {
            get {
                return ResourceManager.GetString("SettingFiO2HighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Flow Low Alarm.
        /// </summary>
        public static string SettingFiO2LowAlarm {
            get {
                return ResourceManager.GetString("SettingFiO2LowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Flow Pattern.
        /// </summary>
        public static string SettingFlowPattern {
            get {
                return ResourceManager.GetString("SettingFlowPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A InCO2 High Alarm(kPa).
        /// </summary>
        public static string SettingInspCO2HighAlarmKpa {
            get {
                return ResourceManager.GetString("SettingInspCO2HighAlarmKpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A InCO2 High Alarm(mmHg).
        /// </summary>
        public static string SettingInspCO2HighAlarmMmhg {
            get {
                return ResourceManager.GetString("SettingInspCO2HighAlarmMmhg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A InCO2 High Alarm(%).
        /// </summary>
        public static string SettingInspCO2HighAlarmPerc {
            get {
                return ResourceManager.GetString("SettingInspCO2HighAlarmPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Insp Press.
        /// </summary>
        public static string SettingInspPress {
            get {
                return ResourceManager.GetString("SettingInspPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Insp Press Max.
        /// </summary>
        public static string SettingInspPressMax {
            get {
                return ResourceManager.GetString("SettingInspPressMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Insp Press Min.
        /// </summary>
        public static string SettingInspPressMin {
            get {
                return ResourceManager.GetString("SettingInspPressMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Insp Time.
        /// </summary>
        public static string SettingInspTime {
            get {
                return ResourceManager.GetString("SettingInspTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Insp Time Max.
        /// </summary>
        public static string SettingInspTimeMax {
            get {
                return ResourceManager.GetString("SettingInspTimeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Insp Time Min.
        /// </summary>
        public static string SettingInspTimeMin {
            get {
                return ResourceManager.GetString("SettingInspTimeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Insp Trig.
        /// </summary>
        public static string SettingInspTrigger {
            get {
                return ResourceManager.GetString("SettingInspTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Disconnection Alarm.
        /// </summary>
        public static string SettingLeakageHighAlarm {
            get {
                return ResourceManager.GetString("SettingLeakageHighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Rebreathing Alarm.
        /// </summary>
        public static string SettingLeakageLowAlarm {
            get {
                return ResourceManager.GetString("SettingLeakageLowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A MinuteVol HighAlarm.
        /// </summary>
        public static string SettingMinuteVolHighAlarm {
            get {
                return ResourceManager.GetString("SettingMinuteVolHighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A MVe High Alarm.
        /// </summary>
        public static string SettingMinuteVolHighExpAlarm {
            get {
                return ResourceManager.GetString("SettingMinuteVolHighExpAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A MVi High Alarm.
        /// </summary>
        public static string SettingMinuteVolHighInspAlarm {
            get {
                return ResourceManager.GetString("SettingMinuteVolHighInspAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A MinuteVol LowAlarm.
        /// </summary>
        public static string SettingMinuteVolLowAlarm {
            get {
                return ResourceManager.GetString("SettingMinuteVolLowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A MVe Low Alarm.
        /// </summary>
        public static string SettingMinuteVolLowExpAlarm {
            get {
                return ResourceManager.GetString("SettingMinuteVolLowExpAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A MVi Low Alarm.
        /// </summary>
        public static string SettingMinuteVolLowInspAlarm {
            get {
                return ResourceManager.GetString("SettingMinuteVolLowInspAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T PEEP.
        /// </summary>
        public static string SettingPeep {
            get {
                return ResourceManager.GetString("SettingPeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PEEP High Alarm.
        /// </summary>
        public static string SettingPeepHighAlarm {
            get {
                return ResourceManager.GetString("SettingPeepHighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PEEP Low Alarm.
        /// </summary>
        public static string SettingPeepLowAlarm {
            get {
                return ResourceManager.GetString("SettingPeepLowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Press High Alarm.
        /// </summary>
        public static string SettingPressHighAlarm {
            get {
                return ResourceManager.GetString("SettingPressHighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Press Low Alarm.
        /// </summary>
        public static string SettingPressLowAlarm {
            get {
                return ResourceManager.GetString("SettingPressLowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Pulse Rate High Alarm.
        /// </summary>
        public static string SettingPulseRateHighAlarm {
            get {
                return ResourceManager.GetString("SettingPulseRateHighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Pulse Rate Low Alarm.
        /// </summary>
        public static string SettingPulseRateLowAlarm {
            get {
                return ResourceManager.GetString("SettingPulseRateLowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T RiseTime Press.
        /// </summary>
        public static string SettingRiseTimePress {
            get {
                return ResourceManager.GetString("SettingRiseTimePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T RiseTime Vol.
        /// </summary>
        public static string SettingRiseTimeVol {
            get {
                return ResourceManager.GetString("SettingRiseTimeVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Set Vol.
        /// </summary>
        public static string SettingSetVol {
            get {
                return ResourceManager.GetString("SettingSetVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Sigh.
        /// </summary>
        public static string SettingSigh {
            get {
                return ResourceManager.GetString("SettingSigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Sigh Perc.
        /// </summary>
        public static string SettingSighPerc {
            get {
                return ResourceManager.GetString("SettingSighPerc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Sigh Rate.
        /// </summary>
        public static string SettingSighRate {
            get {
                return ResourceManager.GetString("SettingSighRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SPO2 High Alarm.
        /// </summary>
        public static string SettingSpO2HighAlarm {
            get {
                return ResourceManager.GetString("SettingSpO2HighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SPO2 Low Alarm.
        /// </summary>
        public static string SettingSpO2LowAlarm {
            get {
                return ResourceManager.GetString("SettingSpO2LowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Target Press.
        /// </summary>
        public static string SettingTargetPress {
            get {
                return ResourceManager.GetString("SettingTargetPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Target Vol.
        /// </summary>
        public static string SettingTargetVol {
            get {
                return ResourceManager.GetString("SettingTargetVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T Target Vol.
        /// </summary>
        public static string SettingTargetVolume {
            get {
                return ResourceManager.GetString("SettingTargetVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Tidal Vol High Alarm.
        /// </summary>
        public static string SettingTidalVolHighAlarm {
            get {
                return ResourceManager.GetString("SettingTidalVolHighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Vte High Alarm.
        /// </summary>
        public static string SettingTidalVolHighExpAlarm {
            get {
                return ResourceManager.GetString("SettingTidalVolHighExpAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Vti High Alarm.
        /// </summary>
        public static string SettingTidalVolHighInspAlarm {
            get {
                return ResourceManager.GetString("SettingTidalVolHighInspAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Tidal Vol Low Alarm.
        /// </summary>
        public static string SettingTidalVolLowAlarm {
            get {
                return ResourceManager.GetString("SettingTidalVolLowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Vte Low Alarm.
        /// </summary>
        public static string SettingTidalVolLowExpAlarm {
            get {
                return ResourceManager.GetString("SettingTidalVolLowExpAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Vti Low Alarm.
        /// </summary>
        public static string SettingTidalVolLowInspAlarm {
            get {
                return ResourceManager.GetString("SettingTidalVolLowInspAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System State.
        /// </summary>
        public static string SystemState {
            get {
                return ResourceManager.GetString("SystemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot Operation Hours.
        /// </summary>
        public static string TotalOperatingTime {
            get {
                return ResourceManager.GetString("TotalOperatingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P Vent Mode.
        /// </summary>
        public static string VentMode {
            get {
                return ResourceManager.GetString("VentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F Working Profile.
        /// </summary>
        public static string WorkingProfile {
            get {
                return ResourceManager.GetString("WorkingProfile", resourceCulture);
            }
        }
    }
}
